# Jekyll configuration
name: Kariem Hashem
description: "Kariem Hashem's personal website and blog"
url: "kariemhashem50.github.io"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
